# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x0bnevo.common\"\x17\n\tUserIdMsg\x12\n\n\x02id\x18\x01 \x01(\x04\"\x1a\n\x0c\x43hannelIdMsg\x12\n\n\x02id\x18\x01 \x01(\x04\"\x84\x01\n\x08UserInfo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\x12\'\n\x06status\x18\x03 \x01(\x0e\x32\x17.nevo.common.UserStatus\x12\r\n\x05muted\x18\x04 \x01(\x08\x12\x10\n\x08\x64\x65\x61\x66\x65ned\x18\x05 \x01(\x08\x12\x10\n\x08group_id\x18\x06 \x01(\r\"\x8c\x01\n\x0b\x43hannelInfo\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tparent_id\x18\x03 \x01(\x04\x12*\n\x08\x63hildren\x18\x04 \x03(\x0b\x32\x18.nevo.common.ChannelInfo\x12$\n\x05users\x18\x05 \x03(\x0b\x32\x15.nevo.common.UserInfo*\xb3\x02\n\nResultCode\x12\x06\n\x02OK\x10\x00\x12\x11\n\rERROR_UNKNOWN\x10\x01\x12\x15\n\x11\x45RROR_AUTH_FAILED\x10\x02\x12\x1b\n\x17\x45RROR_PERMISSION_DENIED\x10\x03\x12\x1b\n\x17\x45RROR_CHANNEL_NOT_FOUND\x10\x04\x12\x1c\n\x18\x45RROR_ALREADY_IN_CHANNEL\x10\x05\x12\x19\n\x15\x45RROR_INVALID_REQUEST\x10\x06\x12\x1b\n\x17\x45RROR_CONNECTION_FAILED\x10\x07\x12\x11\n\rERROR_TIMEOUT\x10\x08\x12\x16\n\x12\x45RROR_CRYPTO_ERROR\x10\n\x12\x1e\n\x1a\x45RROR_NAT_TRAVERSAL_FAILED\x10\x0b\x12\x18\n\x14\x45RROR_USER_NOT_FOUND\x10\x0c*H\n\nUserStatus\x12\x0b\n\x07OFFLINE\x10\x00\x12\n\n\x06ONLINE\x10\x01\x12\x08\n\x04\x41WAY\x10\x02\x12\t\n\x05MUTED\x10\x03\x12\x0c\n\x08\x44\x45\x41\x46\x45NED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESULTCODE']._serialized_start=361
  _globals['_RESULTCODE']._serialized_end=668
  _globals['_USERSTATUS']._serialized_start=670
  _globals['_USERSTATUS']._serialized_end=742
  _globals['_USERIDMSG']._serialized_start=29
  _globals['_USERIDMSG']._serialized_end=52
  _globals['_CHANNELIDMSG']._serialized_start=54
  _globals['_CHANNELIDMSG']._serialized_end=80
  _globals['_USERINFO']._serialized_start=83
  _globals['_USERINFO']._serialized_end=215
  _globals['_CHANNELINFO']._serialized_start=218
  _globals['_CHANNELINFO']._serialized_end=358
# @@protoc_insertion_point(module_scope)
