package com.nevo.voip.core.protocol

enum class MessageType(val id: Int) {
    LOGIN_REQUEST(1),
    LOGIN_RESPONSE(2),
    JOIN_CHANNEL_REQUEST(3),
    LEAVE_CHANNEL_REQUEST(4),
    CREATE_CHANNEL_REQUEST(5),
    DELETE_CHANNEL_REQUEST(6),
    CHANNEL_LIST_UPDATE(7),
    USER_JOINED_CHANNEL(8),
    USER_LEFT_CHANNEL(9),
    USER_SPEAKING(10),
    PTT_TOGGLE(11),
    USER_MUTE_TOGGLE(12),
    SERVER_MESSAGE(13),
    STUN_BIND_REQUEST(14),
    STUN_BIND_RESPONSE(15),
    UDP_PING_REQUEST(16),
    UDP_PING_RESPONSE(17),
    KEY_ROTATION_REQUEST(18),
    KEY_ROTATION_RESPONSE(19),
    ADMIN_AUTH_REQUEST(20),
    ADMIN_AUTH_RESPONSE(21),
    SET_ADMIN_REQUEST(22),
    SET_ADMIN_RESPONSE(23),
    KICK_USER_REQUEST(24),
    KICK_USER_RESPONSE(25),
    BAN_USER_REQUEST(26),
    BAN_USER_RESPONSE(27),
    MOVE_USER_REQUEST(28),
    MOVE_USER_RESPONSE(29),
    CHAT_SEND_REQUEST(30),
    CHAT_BROADCAST(31),
    SET_SERVER_NAME_REQUEST(32),
    SET_SERVER_NAME_RESPONSE(33),
    RENAME_CHANNEL_REQUEST(34),
    RENAME_CHANNEL_RESPONSE(35),
    SPEAKING_STATE(36),
    FILE_LIST_REQUEST(40),
    FILE_LIST_RESPONSE(41),
    FILE_UPLOAD_REQUEST(42),
    FILE_UPLOAD_RESPONSE(43),
    FILE_DOWNLOAD_REQUEST(46),
    FILE_DOWNLOAD_RESPONSE(47),
    FILE_DELETE_REQUEST(49),
    FILE_DELETE_RESPONSE(50),
    // ---- 屏幕共享（proto/control.proto 60-62） ----
    SCREEN_SHARE_START(60),
    SCREEN_SHARE_STOP(61),
    SCREEN_SHARE_STATE(62),
    // ---- 服主绑定（proto/control.proto 70-71） ----
    BIND_OWNER_REQUEST(70),
    BIND_OWNER_RESPONSE(71),
    // ---- 视频通话（proto/control.proto 80-83） ----
    VIDEO_CALL_REQUEST(80),
    VIDEO_CALL_RESPONSE(81),
    VIDEO_CALL_HANGUP(82),
    VIDEO_CALL_PROFILE_UPDATE(83);

    companion object {
        fun fromId(id: Int): MessageType? = entries.find { it.id == id }
    }
}